"""Initial Migration

Revision ID: 6640484e5703
Revises: 
Create Date: 2019-08-07 21:13:06.687109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6640484e5703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('store_sku', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=True),
    sa.Column('club_status_id', sa.Integer(), nullable=True),
    sa.Column('effect_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['club_status_id'], ['club_status.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('customer_store_id', sa.String(length=36), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('effect_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_status_history')
    op.drop_table('subscription')
    op.drop_table('club_status_history')
    op.drop_table('status')
    op.drop_table('club_status')
    op.drop_table('club')
    # ### end Alembic commands ###
